name: Test Backend
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses : actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      #finally build your app with the latest comman
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=maghwa_devops-livecoding -Dsonar.organization=maghwa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml

